version: 2

defaults: &defaults
  working_directory: ~/rta
  docker:
    - image: circleci/node:10

cypress: &cypress
  working_directory: ~/rta
  docker:
    - image: cypress/base:10
      environment:
        ## this enables colors in the output
        TERM: xterm

jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - restore_cache:
          keys:
            - v4-3-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v4-3-dependencies-
      - run:
          name: Install Dependencies
          command: |
            npm install --frozen-lockfile
      - save_cache:
          key: v4-3-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
            # cache Cypress
            - ~/.cache
      - persist_to_workspace:
          root: ~/
          paths:
            - .cache
            - rta
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run lint
  flow:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run flow:check
  e2e:
    <<: *cypress
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          keys:
            - v4-3-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v4-3-dependencies-
      - run: npm run cypress
  tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          keys:
            - v4-3-jest-cache-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v4-3-jest-cache-
      - run: npm run test
      - save_cache:
          key: v4-3-jest-cache-{{ checksum "package-lock.json" }}
          paths:
            - .jestCache
      - persist_to_workspace:
          root: .
          paths: .
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths: .
  build-example:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run example:build && bash .circleci/comment-artifacts.sh
      - store_artifacts:
          path: ./example-build
          destination: example

workflows:
  version: 2
  build:
    jobs:
      - install-dependencies
      - lint:
          requires:
            - install-dependencies
      - flow:
          requires:
            - install-dependencies
      - tests:
          requires:
            - install-dependencies
      - e2e:
          requires:
            - install-dependencies
            - tests
      - build:
          requires:
            - tests
            - e2e
      - build-example:
          requires:
            - tests
            - e2e
          filters:
            branches:
              ignore: master
